# Generated by Django 3.2.6 on 2021-09-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Partner Name')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Partner GST')),
                ('website_uri', models.URLField(max_length=120, verbose_name='Partner website')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Partner Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Partner email')),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Member Name')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile number')),
                ('email', models.EmailField(max_length=254, verbose_name='Member email')),
                ('on_created', models.DateTimeField(auto_now_add=True)),
                ('on_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='partners.partner')),
            ],
        ),
    ]
